ALTER TABLE users
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS full_name VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS bio TEXT NULL,
  ADD COLUMN IF NOT EXISTS date_of_birth DATE NULL,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS website VARCHAR(300) NULL;
