import type { Asset, AssetRequest, Category, Notification } from "./types";

export const fallbackCategories: Category[] = [
  { id: 1, name: "Controllers", slug: "controllers" },
  { id: 2, name: "AI", slug: "ai" },
  { id: 3, name: "UI", slug: "ui" },
  { id: 4, name: "Inventory", slug: "inventory" },
  { id: 5, name: "Dialogue", slug: "dialogue" },
  { id: 6, name: "Save System", slug: "save-system" },
  { id: 7, name: "Multiplayer", slug: "multiplayer" },
  { id: 8, name: "Editor Tools", slug: "editor-tools" },
  { id: 9, name: "VFX", slug: "vfx" },
  { id: 10, name: "Shaders", slug: "shaders" },
  { id: 11, name: "Audio", slug: "audio" },
  { id: 12, name: "Animations", slug: "animations" },
  { id: 13, name: "2D", slug: "2d" },
  { id: 14, name: "3D", slug: "3d" },
  { id: 15, name: "Templates", slug: "templates" },
];

export const fallbackAssets: Asset[] = [
  {
    id: 1,
    title: "Third Person Starter Controller",
    slug: "third-person-starter-controller",
    thumbnail_url: "/mock-assets/controller.png",
    download_url: "https://example.com/downloads/third-person-starter-controller.zip",
    gallery_urls: ["/mock-assets/controller.png"],
    description:
      "A polished movement controller for fast Unity prototyping with camera orbit, jump buffering, slope handling, and animation hooks.",
    features: ["Cinemachine-ready camera rig", "Ground detection and slope support", "Input System bindings", "Clean demo scene"],
    unity_version: "2022.3 LTS+",
    file_size: "38 MB",
    download_count: 214,
    rating: 4.8,
    category: fallbackCategories[0],
    credit_cost: 80,
    changelog: "Initial V1 release with improved camera collision and controller presets.",
    version: "1.0.0",
    tags: ["controller", "third-person", "starter"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Modular Inventory Kit",
    slug: "modular-inventory-kit",
    thumbnail_url: "/mock-assets/inventory.png",
    download_url: "https://example.com/downloads/modular-inventory-kit.zip",
    gallery_urls: ["/mock-assets/inventory.png"],
    description:
      "A drag-and-drop inventory framework with item definitions, stacks, quick slots, and save/load integration.",
    features: ["Grid and hotbar layouts", "ScriptableObject item database", "Stack splitting", "JSON save adapter"],
    unity_version: "2021.3 LTS+",
    file_size: "52 MB",
    download_count: 168,
    rating: 4.7,
    category: fallbackCategories[3],
    credit_cost: 120,
    changelog: "Added quick slot events and UI Toolkit sample.",
    version: "1.2.0",
    tags: ["inventory", "items", "ui"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    title: "Enemy AI Patrol Pack",
    slug: "enemy-ai-patrol-pack",
    thumbnail_url: "/mock-assets/ai.png",
    download_url: "https://example.com/downloads/enemy-ai-patrol-pack.zip",
    gallery_urls: ["/mock-assets/ai.png"],
    description:
      "State-machine enemy AI for stealth, patrol, chase, attack, and return-to-route behavior.",
    features: ["Finite state machine", "Waypoint patrol editor", "Vision cone helper", "NavMesh examples"],
    unity_version: "2022.3 LTS+",
    file_size: "44 MB",
    download_count: 132,
    rating: 4.6,
    category: fallbackCategories[1],
    credit_cost: 100,
    changelog: "Balanced chase transitions and added alert cooldowns.",
    version: "1.1.0",
    tags: ["ai", "enemy", "navmesh"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    title: "Neon UI HUD Template",
    slug: "neon-ui-hud-template",
    thumbnail_url: "/mock-assets/ui.png",
    download_url: "https://example.com/downloads/neon-ui-hud-template.zip",
    gallery_urls: ["/mock-assets/ui.png"],
    description:
      "A responsive HUD template for health, stamina, XP, notifications, menus, and controller-friendly navigation.",
    features: ["Prefab-driven HUD modules", "Animated notification stack", "Gamepad navigation", "Light and dark variants"],
    unity_version: "2021.3 LTS+",
    file_size: "29 MB",
    download_count: 191,
    rating: 4.9,
    category: fallbackCategories[2],
    credit_cost: 60,
    changelog: "Added scalable safe-area layout presets.",
    version: "1.0.3",
    tags: ["ui", "hud", "template"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const fallbackRequests: AssetRequest[] = [
  {
    id: 1,
    title: "Quest Journal System",
    unity_asset_store_link: "https://assetstore.unity.com/",
    reason: "A reusable quest journal would help RPG and adventure prototypes move faster.",
    status: "open",
    vote_count: 12,
    voted: false,
    requested_by: "Unity Builder",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "Dialogue Graph Editor",
    unity_asset_store_link: "https://assetstore.unity.com/",
    reason: "A node-based dialogue editor with branching choices and localization hooks.",
    status: "planned",
    vote_count: 9,
    voted: false,
    requested_by: "Unity Builder",
    created_at: new Date().toISOString(),
  },
];

export const fallbackNotifications: Notification[] = [
  {
    id: 1,
    title: "Daily Reward Available",
    body: "Come back every 24 hours to keep your 7-day credit streak alive.",
    type: "daily_reward",
    expires_at: null,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: "New Asset Released",
    body: "Third Person Starter Controller is now available in the catalog.",
    type: "new_asset",
    expires_at: null,
    created_at: new Date().toISOString(),
  },
];
